version: '1.0'
name: pipeline-20260309
displayName: pipeline-20260309
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: stage-9f5ba408
    displayName: '1'
    strategy: naturally
    trigger: auto
    executor:
      - huangrichao_admin
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: index
        notify: []
        strategy:
          retry: '0'
